name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100-preview8-013656'

    - name: Build
      run: dotnet build -bl

    - uses: actions/upload-artifact@master
      if: always
      with:
        name: Build logs
        path: '**/*.binlog'

    - name: Test
      run: dotnet test --no-build
