name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - run: |
          echo "::add-matcher::$PWD/csc.json"
          echo '##[error]SnippetParsing.cs(7,2): error CS1022: Type or namespace definition, or end-of-file expected [/home/runner/work/bumblebee/bumblebee/BumblebeeTests/BumblebeeTests.csproj]'
      - uses: actions/checkout@master
    
#      - name: Install .NET Core SDK
 #       uses: actions/setup-dotnet@v1
  #      with:
   #       dotnet-version: '3.0.100-preview8-013656'

#      - name: Build and test
 #       run: dotnet test
