name: CI

on:
  pull_request:
    branches:
    - *


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Run a one-line script
      run: dotnet test
